In [1]:
import yfinance as yf
import pandas as pd

In [ ]:
lt = yf.Ticker("LT.NS")        # NSE symbol must end with .NS
data = lt.history(period="ytd") 

lt_data = pd.DataFrame(data)
print(lt_data.shape)
lt_data.tail()

(41, 7)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-02-23 00:00:00+05:30,4395.600098,4431.600098,4371.700195,4418.100098,2122782,0.0,0.0
2026-02-24 00:00:00+05:30,4415.500000,4440.000000,4228.100098,4259.200195,3673070,0.0,0.0
2026-02-25 00:00:00+05:30,4270.000000,4344.899902,4254.200195,4298.500000,2481469,0.0,0.0
2026-02-26 00:00:00+05:30,4304.899902,4340.000000,4278.299805,4286.500000,2370148,0.0,0.0
2026-02-27 00:00:00+05:30,4288.899902,4304.700195,4254.399902,4278.299805,2357853,0.0,0.0

In [ ]:
airtel = yf.Ticker("BHARTIARTL.NS")
data = airtel.history(period="ytd")

airtel_data = pd.DataFrame(data)
print(airtel_data.shape)
airtel_data.tail()

(41, 7)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-02-23 00:00:00+05:30,1994.000000,2000.500000,1983.900024,1997.300049,3728878,0.0,0.0
2026-02-24 00:00:00+05:30,1997.300049,1997.300049,1921.800049,1941.000000,10006761,0.0,0.0
2026-02-25 00:00:00+05:30,1955.000000,1961.800049,1904.000000,1913.400024,8285195,0.0,0.0
2026-02-26 00:00:00+05:30,1914.000000,1935.000000,1904.500000,1929.599976,10795028,0.0,0.0
2026-02-27 00:00:00+05:30,1910.000000,1915.000000,1870.099976,1879.300049,13754648,0.0,0.0

In [15]:
nifty = yf.Ticker("^NSEI")
print(nifty.fast_info)
data = nifty.history(period="ytd")

nifty_data = pd.DataFrame(data)

print(nifty_data.shape)
nifty_data.tail()

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']
(40, 7)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-02-23 00:00:00+05:30,25678.400391,25771.449219,25609.349609,25713.000000,313700,0.0,0.0
2026-02-24 00:00:00+05:30,25641.800781,25641.800781,25327.599609,25424.650391,439100,0.0,0.0
2026-02-25 00:00:00+05:30,25512.599609,25652.599609,25428.199219,25482.500000,414200,0.0,0.0
2026-02-26 00:00:00+05:30,25556.300781,25572.949219,25400.949219,25496.550781,405200,0.0,0.0
2026-02-27 00:00:00+05:30,25459.849609,25476.400391,25141.300781,25178.650391,438900,0.0,0.0

In [16]:
banknifty = yf.Ticker("^NSEBANK")
print(banknifty.fast_info)
data = banknifty.history(period="ytd")

banknifty_data = pd.DataFrame(data)

print(banknifty_data.shape)
banknifty_data.tail()

lazy-loading dict with keys = ['currency', 'dayHigh', 'dayLow', 'exchange', 'fiftyDayAverage', 'lastPrice', 'lastVolume', 'marketCap', 'open', 'previousClose', 'quoteType', 'regularMarketPreviousClose', 'shares', 'tenDayAverageVolume', 'threeMonthAverageVolume', 'timezone', 'twoHundredDayAverage', 'yearChange', 'yearHigh', 'yearLow']
(40, 7)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-02-23 00:00:00+05:30,61145.550781,61517.800781,61029.148438,61264.250000,841900,0.0,0.0
2026-02-24 00:00:00+05:30,61392.101562,61435.648438,60801.851562,61047.300781,587700,0.0,0.0
2026-02-25 00:00:00+05:30,61175.050781,61317.550781,60816.750000,61043.351562,321600,0.0,0.0
2026-02-26 00:00:00+05:30,61193.898438,61284.750000,60813.300781,61187.699219,602700,0.0,0.0
2026-02-27 00:00:00+05:30,61057.449219,61086.449219,60438.949219,60529.000000,369200,0.0,0.0